GITHUB_TEMPLATE_REPO_URL: 'philipritchey/autograded-assignment-template'
GITHUB_AUTOGRADER_CORE_REPO: 'autograder-core'
GITHUB_COURSE_ORGANIZATION: 'AutograderFrontend'
ASSIGNMENTS_BASE_PATH: 'assignment-repos/'