GITHUB_ACCESS_TOKEN: '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'
GITHUB_TEMPLATE_REPO_URL: 'philipritchey/autograded-assignment-template'
GITHUB_COURSE_ORGANIZATION: 'AutograderFrontend'
ASSIGNMENTS_BASE_PATH: 'assignment-repos/'