name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # scan_ruby:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: .ruby-version
  #         bundler-cache: true

  #     - name: Scan for common Rails security vulnerabilities using static analysis
  #       run: bundle exec brakeman --no-pager

  rubycritic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RubyCritic
        run: bundle exec rubycritic --no-browser --format console app lib config

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop -f github

  # cucumber:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: .ruby-version
  #         bundler-cache: true

  #     - name: Install dependencies
  #       run: bundle install

  #     - name: Run database migrations
  #       run: bundle exec rails db:migrate



  # rspec:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: .ruby-version
  #         bundler-cache: true

  #     - name: Install dependencies
  #       run: bundle install





  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run database migrations
        run: bundle exec rails db:migrate RAILS_ENV=test

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run Cucumber
        run: bundle exec cucumber features/live_update_points.feature

      # - name: Code Climate Coverage Action
      #   uses: paambaati/codeclimate-action@v9.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: bundle exec rake tests:run
      #     coverageLocations: coverage/.resultset.json
      #     debug: false
      #     verifyDownload: true
      #     verifyEnvironment: true


  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: .ruby-version
  #         bundler-cache: true

  #     - name: Deploy to Heroku
  #       run: |
  #         heroku login -i
  #         heroku create
  #         git push heroku main
  #         heroku run rake db:migrate
  #         heroku run rake db:seed


  # scan_js:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: .ruby-version
  #         bundler-cache: true

  #     - name: Scan for security vulnerabilities in JavaScript dependencies
  #       run: bin/importmap audit